### ISSUE TITLE
How to set number of samples in mask?

### ISSUE THREAD

**Issue by hkaggarwal** [cagladbahadir/LOUPE#1]
@cagladbahadir, 

Can you please tell the relation between sparsity-level parameter lambda and the number of samples?

If I have to do 50% sampling i.e. I want to acquire 50% samples then how to set the lambda value?

Also, the default value of lambda is 0.98. It is corresponding to how much sparsity?

Thank you

**Comment by cagladbahadir** [comment]
Hello @hkaggarwal,

As lambda increases on the reconstruction loss the weight on sparsity is decreased therefore the under-sampling rate decreases (sampling rate R is the acceleration factor, e.g. R=4 means acquiring 25% of k-space.) Therefore if you want to increase your sampling rate R, i.e. sample less in the k-space, you should decrease lambda on the reconstruction loss (which increases the weight on the sampling sparsity term). For our dataset, 0.98 corresponded to 10% under-sampling, however this should be different for different data-sets. Also, please read the preprocessing part in our paper carefully to see normalizations etc. The images were normalized between 0-1. The model is initialized with uniform random so this results in 50% sampling. You might want to initialized to something higher and find the appropriate lambda for your data set to achieve 50%. 

Best,

Cagla
