### ISSUE TITLE
the mask provided is not like Gaussian mask

### ISSUE THREAD

**Issue by chuan1093** [cagladbahadir/LOUPE#3]
When I plot the masks provided in `legacy/Mask_Configurations/`, I found that masks loaded from `Mymodel` is not like `Gaussian`, which is very strange. As stated in your paper, the masks loaded from `Mymodel` should mainly sample the center part.

Here is the code to plot the masks provided.
```
mask_dir = 'legacy/Mask_Configurations/'
mask_names = [
    'EPI_5.npy',
    'EPI_10.npy',
    'Gaussian_5.npy',
    'Gaussian_10.npy',
    'Mymodel_5.npy',
    'Mymodel_10.npy',
    'Uniform_5.npy',
    'Uniform_10.npy'
]
for mask_name in mask_names:
    path = os.path.join(mask_dir, mask_name)
    mask = np.load(path)
    plt.figure()
    plt.imshow(mask, cmap='gray')
    plt.show()
```
Here is the plot of `Gaussian_10.npy`:
![image](https://user-images.githubusercontent.com/41619684/77396016-cfd0f780-6ddd-11ea-8a13-007baf0fae5f.png)
Here is the plot of `Mymodel_10.npy`:
![image](https://user-images.githubusercontent.com/41619684/77396025-d52e4200-6ddd-11ea-98a9-d14f75319926.png)

Is there something wrong with my operation or understanding?
Please help me. Thanks a lot!

**Comment by adalca** [comment]
@chuan1093  it sounds like you identified the problem, since you closed the issue?

**Comment by chuan1093** [comment]
Yes, I've identified the problem. I forgot to use `np.fft.ifftshift` for `Mymodel_10.npy`. Thanks for your attention.
